In [14]:
import pandas as pd
import numpy as np
import seaborn as sns
import sys

import random
import math
import dalmatian

## Concatentate Phylogic outputs into one spreadsheet

### Mut ccfs files

In [ ]:

pat_1598 = pd.read_csv("/Users/lmartin/Documents/2020/new_pon_breast_phylo/1598_new_pon_results/1598.mut_ccfs.txt", sep='\t')
pat_1002 = pd.read_csv("/Users/lmartin/Documents/2020/new_pon_breast_phylo/1002_pre_post_updated/1002_with_pre_post.mut_ccfs.txt", sep='\t',
                      low_memory=False)

#pat_1547 = pd.read_csv("/Users/lmartin/Documents/2020/new_pon_breast_phylo/1547_passed_muts_results/1547.mut_ccfs.txt", sep='\t')

pat_1078 = pd.read_csv("/Users/lmartin/Documents/2020/new_pon_breast_phylo/1078_new_pon_results/1078.mut_ccfs.txt", sep='\t')


pat_1326 = pd.read_csv("/Users/lmartin/Documents/2020/new_pon_breast_phylo/1326_firecloud_phylo/1326_cfDNA_high_purity.mut_ccfs.txt", sep='\t')
pat_1644 = pd.read_csv("/Users/lmartin/Documents/2020/new_pon_breast_phylo/1644_passed_muts_results/1644.mut_ccfs.txt", sep='\t')

pat_2819 = pd.read_csv("/Users/lmartin/Documents/2020/new_pon_breast_phylo/2819_passed_muts_results/2819.mut_ccfs.txt", sep='\t',
                      low_memory=False)
pat_2389 = pd.read_csv("/Users/lmartin/Documents/2023/2389_multiple_6_bl_tree_0515/2389_multiple_6_bl_tree_v1/2389_multiple_6.mut_ccfs.txt", sep='\t',
                      low_memory=False)

pat_2974 = pd.read_csv("/Users/lmartin/Documents/2020/new_pon_breast_phylo/2974_new_pon_results/2974.mut_ccfs.txt", sep='\t')

pat_1035 = pd.read_csv("/Users/lmartin/Documents/2020/new_pon_breast_phylo/1035_with_indel/1035.mut_ccfs.txt", sep='\t')

pat_1534 = pd.read_csv('/Users/lmartin/Documents/2023/RA_1534_rerun_phylogic/1534_phylo_120423/1534.mut_ccfs.txt',sep='\t')



pats_list = [pat_1598, pat_1078,
            pat_1326, pat_1644, pat_2819, pat_2974, pat_1035, pat_1534]

## Mutational signature output file

In [ ]:
signatures = pd.read_csv('/Users/lmartin/2023/Autopsy_output_sigs_using_cosmic2/autopsy_with_cosmic2_sigs_08212023,tsv',sep='\t')

### Cluster ccfs files

In [ ]:
pat_1002_cluster_ccfs = pd.read_csv("/Users/lmartin/Documents/2020/new_pon_breast_phylo/1002_pre_post_updated/1002_with_pre_post.cluster_ccfs.txt", sep='\t',
                      low_memory=False)

pat_1598_cluster = pd.read_csv("/Users/lmartin/Documents/2020/new_pon_breast_phylo/1598_new_pon_results/1598.cluster_ccfs.txt", sep='\t')

#pat_1547 = pd.read_csv("/Users/lmartin/Documents/2020/new_pon_breast_phylo/1547_passed_muts_results/1547.mut_ccfs.txt", sep='\t')

pat_1078_cluster = pd.read_csv("/Users/lmartin/Documents/2020/new_pon_breast_phylo/1078_new_pon_results/1078.cluster_ccfs.txt", sep='\t')


pat_1326_cluster = pd.read_csv("/Users/lmartin/Documents/2020/new_pon_breast_phylo/1326_firecloud_phylo/1326_cfDNA_high_purity.cluster_ccfs.txt", sep='\t')
pat_1644_cluster = pd.read_csv("/Users/lmartin/Documents/2020/new_pon_breast_phylo/1644_passed_muts_results/1644.cluster_ccfs.txt", sep='\t')

pat_2819_cluster = pd.read_csv("/Users/lmartin/Documents/2020/new_pon_breast_phylo/2819_passed_muts_results/2819.cluster_ccfs.txt", sep='\t',
                      low_memory=False)

pat_2389_cluster_ccfs = pd.read_csv("/Users/lmartin/Documents/2023/2389_multiple_6_bl_tree_0515/2389_multiple_6_bl_tree_v1/2389_multiple_6.cluster_ccfs.txt", sep='\t')

pat_2974_cluster = pd.read_csv("/Users/lmartin/Documents/2020/new_pon_breast_phylo/2974_new_pon_results/2974.cluster_ccfs.txt", sep='\t')

pat_1035_cluster = pd.read_csv("/Users/lmartin/Documents/2020/new_pon_breast_phylo/1035_with_indel/1035.cluster_ccfs.txt", sep='\t')

pat_1534_cluster = pd.read_csv('/Users/lmartin/Documents/2023/RA_1534_rerun_phylogic/1534_phylo_120423/1534.cluster_ccfs.txt',sep='\t')



pats_cluster_ccfs_list = [pat_1598_cluster, pat_1078_cluster,
            pat_1326_cluster, pat_1644_cluster, pat_2819_cluster, pat_2974_cluster, pat_1035_cluster, pat_1534_cluster]

### Buildtree Posteriors

In [9]:
def insert_pat_col(input_df, pat_id):
    patient_ID_col = [pat_id]*len(input_df)
    input_df.insert(loc=0,column='Patient_ID',value=patient_ID_col)
    return input_df

In [11]:
pat_1002_buildtree = pd.read_csv("/Users/lmartin/Documents/2020/new_pon_breast_phylo/1002_bl_tree/1002_build_tree_posteriors.tsv", sep='\t')
pat_1002_buildtree_add_pat = insert_pat_col(pat_1002_buildtree,'1002')

pat_1547_buildtree = pd.read_csv("/Users/lmartin/Documents/2020/new_pon_breast_phylo/ ", sep='\t')
pat_1547_buildtree_add_pat = insert_pat_col(pat_1078_buildtree,'1547')

pat_1078_buildtree = pd.read_csv("/Users/lmartin/Documents/2020/new_pon_breast_phylo/1078_new_pon_results/1078_build_tree_posteriors.tsv", sep='\t')
pat_1078_buildtree_add_pat = insert_pat_col(pat_1078_buildtree,'1078')

pat_1598_buildtree = pd.read_csv("/Users/lmartin/Documents/2020/new_pon_breast_phylo/1598_new_pon_results/1598_build_tree_posteriors.tsv", sep='\t')
pat_1598_buildtree_add_pat = insert_pat_col(pat_1002_buildtree,'1598')

pat_1326_buildtree = pd.read_csv("/Users/lmartin/Documents/2020/new_pon_breast_phylo/1326_firecloud_phylo/1326_cfDNA_high_purity_build_tree_posteriors.tsv", sep='\t')
pat_1326_buildtree_add_pat = insert_pat_col(pat_1002_buildtree,'1326')

pat_1644_buildtree = pd.read_csv("/Users/lmartin/Documents/2020/new_pon_breast_phylo/1644_passed_muts_results/1644_build_tree_posteriors.tsv", sep='\t')
pat_1644_buildtree_add_pat = insert_pat_col(pat_1002_buildtree,'1644')

pat_2819_buildtree = pd.read_csv("/Users/lmartin/Documents/2020/new_pon_breast_phylo/2819_passed_muts_results/2819_build_tree_posteriors.tsv", sep='\t')
pat_2819_buildtree_add_pat = insert_pat_col(pat_2819_buildtree,'2819')

pat_2389_buildtree = pd.read_csv("/Users/lmartin/Documents/2023/2389_multiple_6_bl_tree_0515/2389_multiple_6_bl_tree_v1/2389_multiple_6_build_tree_posteriors.tsv", sep='\t')
pat_2389_buildtree_add_pat = insert_pat_col(pat_2389_buildtree,'2389')

pat_2974_buildtree = pd.read_csv("/Users/lmartin/Documents/2020/new_pon_breast_phylo/2974_new_pon_results/2974_build_tree_posteriors.tsv", sep='\t')
pat_2974_buildtree_add_pat = insert_pat_col(pat_2974_buildtree,'2974')

pat_1534_buildtree = pd.read_csv("/Users/lmartin/Documents/2023/RA_1534_rerun_phylogic/1534_phylo_120423/1534_build_tree_posteriors.tsv", sep='\t')
pat_1534_buildtree_add_pat = insert_pat_col(pat_2819_buildtree,'1534')

pat_1035_buildtree = pd.read_csv("/Users/lmartin/Documents/2020/new_pon_breast_phylo/1035_with_indel/1035_build_tree_posteriors.tsv", sep='\t')
pat_1035_buildtree_add_pat = insert_pat_col(pat_1035_buildtree,'1035')

pat_1113_buildtree = pd.read_csv("/Users/lmartin/Documents/2020/new_pon_breast_phylo/1113_vm_phylo_results/1113_build_tree_posteriors.tsv", sep='\t')
pat_1113_buildtree_add_pat = insert_pat_col(pat_1113_buildtree,'1113')

pat_1045_buildtree = pd.read_csv("/Users/lmartin/Documents/2020/new_pon_breast_phylo/1045_vm_phylo_results/1045_build_tree_posteriors.tsv", sep='\t')
pat_1045_buildtree_add_pat = insert_pat_col(pat_1045_buildtree,'1045')

pat_1558_buildtree = pd.read_csv("/Users/lmartin/Documents/2020/new_pon_breast_phylo/1002_bl_tree/1002_build_tree_posteriors.tsv", sep='\t')
pat_1558_buildtree_add_pat = insert_pat_col(pat_1558_buildtree,'1558')

pat_2542_buildtree = pd.read_csv("/Users/lmartin/Documents/2020/new_pon_breast_phylo/1002_bl_tree/1002_build_tree_posteriors.tsv", sep='\t')
pat_2542_buildtree_add_pat = insert_pat_col(pat_2542_buildtree,'2542')

buildtrees=[pat_1078_buildtree_add_pat,pat_1598_buildtree_add_pat,pat_1326_buildtree_add_pat,pat_1644_buildtree_add_pat,
            pat_2819_buildtree_add_pat,pat_2389_buildtree_add_pat,pat_2974_buildtree_add_pat,pat_1534_buildtree_add_pat,
            pat_1035_buildtree_add_pat,pat_1113_buildtree_add_pat,pat_1045_buildtree_add_pat]

buildtree_df = pd.concat(buildtrees)
buildtree_df

## cell populations

In [6]:
#pat_1002_cellpop = pd.read_csv("/Users/lmartin/Documents/2020/new_pon_breast_phylo/1002_bl_tree/1002_cell_population_abundances.tsv", sep='\t')

#pat_1547_cellpop = pd.read_csv("/Users/lmartin/Documents/2020/new_pon_breast_phylo/1547_passed_muts_results/1547.mut_ccfs.txt", sep='\t')

pat_1078_cellpop = pd.read_csv("/Users/lmartin/Documents/2020/new_pon_breast_phylo/1078_new_pon_results/1078_cell_population_abundances.tsv", sep='\t')
pat_1598_cellpop = pd.read_csv("/Users/lmartin/Documents/2020/new_pon_breast_phylo/1598_new_pon_results/1598_cell_population_abundances.tsv", sep='\t')

pat_1326_cellpop = pd.read_csv("/Users/lmartin/Documents/2020/new_pon_breast_phylo/1326_firecloud_phylo/1326_cfDNA_high_purity_cell_population_abundances.tsv", sep='\t')
pat_1644_cellpop = pd.read_csv("/Users/lmartin/Documents/2020/new_pon_breast_phylo/1644_passed_muts_results/1644_cell_population_abundances.tsv", sep='\t')

pat_2819_cellpop = pd.read_csv("/Users/lmartin/Documents/2020/new_pon_breast_phylo/2819_passed_muts_results/2819_cell_population_abundances.tsv", sep='\t')
pat_2389_cellpop = pd.read_csv("/Users/lmartin/Documents/2023/2389_multiple_6_bl_tree_0515/2389_multiple_6_bl_tree_v1/2389_multiple_6_cell_population_abundances.tsv", sep='\t')

pat_2974_cellpop = pd.read_csv("/Users/lmartin/Documents/2020/new_pon_breast_phylo/2974_new_pon_results/2974_cell_population_abundances.tsv", sep='\t')
pat_1534_cellpop = pd.read_csv("/Users/lmartin/Documents/2023/RA_1534_rerun_phylogic/1534_phylo_120423/1534_cell_population_abundances.tsv", sep='\t')

pat_1035_cellpop = pd.read_csv("/Users/lmartin/Documents/2020/new_pon_breast_phylo/1035_with_indel/1035_cell_population_abundances.tsv", sep='\t')

pat_1113_cellpop = pd.read_csv('/Users/lmartin/Documents/2020/new_pon_breast_phylo/1113_vm_phylo_results/1113_cell_population_abundances.tsv',sep='\t')
pat_1045_cellpop = pd.read_csv('/Users/lmartin/Documents/2020/new_pon_breast_phylo/1045_vm_phylo_results/1045_cell_population_abundances.tsv',sep='\t')

cellpops=[pat_1078_cellpop,pat_1598_cellpop,pat_1326_cellpop,pat_1644_cellpop,pat_2819_cellpop,
         pat_2389_cellpop,pat_2974_cellpop,pat_1534_cellpop,pat_1035_cellpop,pat_1113_cellpop,
         pat_1045_cellpop]


cellpop_df = pd.concat(cellpops)
cellpop_df

    Patient_ID   Sample_ID       Cell_population  Cell_abundance
0         1078          10                   CL1               0
1         1078          10               CL1_CL2               0
2         1078          10           CL1_CL2_CL3              98
3         1078          10           CL1_CL2_CL4               1
4         1078          10           CL1_CL2_CL5               1
..         ...         ...                   ...             ...
325       1045  cfDNA_2971      CL1_CL2_CL3_CL11               0
326       1045  cfDNA_2971      CL1_CL2_CL3_CL12               1
327       1045  cfDNA_2971      CL1_CL2_CL3_CL13               1
328       1045  cfDNA_2971  CL1_CL2_CL3_CL9_CL14              10
329       1045  cfDNA_2971      CL1_CL2_CL3_CL15               1

[1454 rows x 4 columns]

## Absolute CN by sample

In [ ]:
## current best file found needs added samples / patients

In [13]:
absolute_cn = pd.read_csv('/Users/lmartin/Documents/2020/autopsy_copy_number/all_cdk4_add_1035_igv.seg',sep='\t')
absolute_cn

,Sample,Chromosome,Start Position,End Position,Start,End,Num_Probes,Seg_CN
0,T01027-3,1,12176,94643659,12176,94643659,7210,0.000000
1,T01027-3,1,94645397,104160689,94645397,104160689,362,-1.000000
2,T01027-3,1,107599965,144363924,107599965,144363924,1207,0.000000
3,T01027-3,1,144520739,147131922,144520739,147131922,514,0.000000
4,T01027-3,1,147142061,147380734,147142061,147380734,3,-inf
...,...,...,...,...,...,...,...,...
18558,1035_20.tsv,21,9907370,31874299,9907370,31874299,321,1.000000
18559,1035_20.tsv,21,31914039,48084246,31914039,48084246,1348,0.584963
18560,1035_20.tsv,22,16287569,21567422,16287569,21567422,557,0.584963
18561,1035_20.tsv,22,21579761,25007131,21579761,25007131,372,0.000000
18562,1035_20.tsv,22,25019815,51237388,25019815,51237388,2500,0.000000

## Mutsig

### mutsig on pats

In [ ]:
patients_sig_genes = pd.read_csv('/Users/lmartin/Documents/2023/CDK4_mutsig_added_pats/on_patients_v3/0/mutsig_results/outdir/sig_genes.txt',sep='\t')

patients_counts_and_rates = pd.read_csv('/Users/lmartin/Documents/2023/CDK4_mutsig_added_pats/on_patients_v3/0/mutsig_results/outdir/patient_counts_and_rates.txt',sep='\t')

### mutsig on clones

In [ ]:
clones_sig_genes = pd.read_csv('on_clones_v3/0/mutsig_results/outdir/sig_genes.txt',sep='\t')

### mutsig on subclones

In [ ]:
subclones_sig_genes = pd.read_csv('on_subclones_v3/0/mutsig_results/outdir/sig_genes.txt',sep='\t')

## write all results to one spreadsheet

In [ ]:
with pd.ExcelWriter('Extended_Data_Table2_Phylogic.xlsx') as writer:  
    mutccfs_df.to_excel(writer, sheet_name='Phylogic MutCCFs')
    clusterccfs_df.to_excel(writer, sheet_name='Phylogic ClusterCCFs')
    buildtree_df.to_excel(writer, sheet_name='BuildTree Posteriors')
    cellpop_df.to_excel(writer, sheet_name='Cell Populations')
    absolute_cn_df.to_excel(writer, sheet_name='Sample_CNV')