In [38]:
import pandas as pd
import numpy as np
import seaborn as sns
import sys

import random
import math
import dalmatian

## Concatentate Phylogic outputs into one spreadsheet

### Mut ccfs files

In [6]:

pat_1598 = pd.read_csv("/Users/lmartin/Documents/2020/new_pon_breast_phylo/1598_new_pon_results/1598.mut_ccfs.txt", sep='\t')



pat_1078 = pd.read_csv("/Users/lmartin/Documents/2020/new_pon_breast_phylo/1078_new_pon_results/1078.mut_ccfs.txt", sep='\t')


pat_1326 = pd.read_csv("/Users/lmartin/Documents/2020/new_pon_breast_phylo/1326_firecloud_phylo/1326_cfDNA_high_purity.mut_ccfs.txt", sep='\t')
pat_1644 = pd.read_csv("/Users/lmartin/Documents/2020/new_pon_breast_phylo/1644_passed_muts_results/1644.mut_ccfs.txt", sep='\t')

pat_2819 = pd.read_csv("/Users/lmartin/Documents/2020/new_pon_breast_phylo/2819_passed_muts_results/2819.mut_ccfs.txt", sep='\t',
                      low_memory=False)
pat_2389 = pd.read_csv("/Users/lmartin/Documents/2023/2389_multiple_6_bl_tree_0515/2389_multiple_6_bl_tree_v1/2389_multiple_6.mut_ccfs.txt", sep='\t',
                      low_memory=False)

pat_2974 = pd.read_csv("/Users/lmartin/Documents/2020/new_pon_breast_phylo/2974_new_pon_results/2974.mut_ccfs.txt", sep='\t')

pat_1035 = pd.read_csv("/Users/lmartin/Documents/2020/new_pon_breast_phylo/1035_with_indel/1035.mut_ccfs.txt", sep='\t')

pat_1002 = pd.read_csv('~/Documents/2020/new_pon_breast_phylo/1002_pre_post_updated/1002_with_pre_post.mut_ccfs.txt',sep='\t',
                          low_memory=False)
pat_1534 = pd.read_csv('~/Documents/2024/RA_1534_vm_new_bams/RA_1534_bl_TBX/1534_bl_TBX/1534.mut_ccfs.txt',sep='\t')

pat_1547 = pd.read_csv('~/Documents/2020/new_pon_breast_phylo/1547_0915/1547_newer_bl_tree/1547.mut_ccfs.txt',sep='\t',
                          low_memory=False)

pat_1558 = pd.read_csv('~/Documents/2023/RA_1558_fix_pies/take_3/1558_fix_pies_v3/1558.mut_ccfs.txt',sep='\t')

pat_2542 = pd.read_csv('~/Documents/2023/RA_2542_PIK3CA/2542_high_purity_v6_morebl_moreiter_results/2542_high_purity_v6_morebl_moreiter.mut_ccfs.txt',sep='\t')

pat_1045 = pd.read_csv("/Users/lmartin/Documents/2020/new_pon_breast_phylo/1045_vm_phylo_results/1045.mut_ccfs.txt",sep='\t',low_memory=False)

pat_1113 =pd.read_csv("/Users/lmartin/Documents/2020/new_pon_breast_phylo/1113_vm_phylo_results/1113.mut_ccfs.txt",sep='\t')

pats_list = [pat_1002, pat_1547, pat_1598, pat_1078, pat_1045, pat_1113, pat_2389,
            pat_1326, pat_1644, pat_2819, pat_2974, pat_1035, pat_1534, pat_1558, pat_2542]

In [7]:
len(pats_list)

15

In [8]:
mut_ccfs_df = pd.concat(pats_list)

## Mutational signature output file

In [14]:
signatures = pd.read_csv('/Users/lmartin/Documents/2024/031924_CDK4_sigs_cosmic2_diff2542/autopsy_with_cosmic2_sigs_031924.tsv',sep='\t')

### Cluster ccfs files

In [15]:
pat_1002_cluster = pd.read_csv("/Users/lmartin/Documents/2020/new_pon_breast_phylo/1002_pre_post_updated/1002_with_pre_post.cluster_ccfs.txt", sep='\t',
                      low_memory=False)

pat_1598_cluster = pd.read_csv("/Users/lmartin/Documents/2020/new_pon_breast_phylo/1598_new_pon_results/1598.cluster_ccfs.txt", sep='\t')



pat_1078_cluster = pd.read_csv("/Users/lmartin/Documents/2020/new_pon_breast_phylo/1078_new_pon_results/1078.cluster_ccfs.txt", sep='\t')


pat_1326_cluster = pd.read_csv("/Users/lmartin/Documents/2020/new_pon_breast_phylo/1326_firecloud_phylo/1326_cfDNA_high_purity.cluster_ccfs.txt", sep='\t')
pat_1644_cluster = pd.read_csv("/Users/lmartin/Documents/2020/new_pon_breast_phylo/1644_passed_muts_results/1644.cluster_ccfs.txt", sep='\t')

pat_2819_cluster = pd.read_csv("/Users/lmartin/Documents/2020/new_pon_breast_phylo/2819_passed_muts_results/2819.cluster_ccfs.txt", sep='\t',
                      low_memory=False)

pat_2389_cluster = pd.read_csv("/Users/lmartin/Documents/2023/2389_multiple_6_bl_tree_0515/2389_multiple_6_bl_tree_v1/2389_multiple_6.cluster_ccfs.txt", sep='\t')

pat_2974_cluster = pd.read_csv("/Users/lmartin/Documents/2020/new_pon_breast_phylo/2974_new_pon_results/2974.cluster_ccfs.txt", sep='\t')

pat_1035_cluster = pd.read_csv("/Users/lmartin/Documents/2020/new_pon_breast_phylo/1035_with_indel/1035.cluster_ccfs.txt", sep='\t')


pat_1534_cluster = pd.read_csv('~/Documents/2024/RA_1534_vm_new_bams/RA_1534_bl_TBX/1534_bl_TBX/1534.cluster_ccfs.txt',sep='\t')

pat_1547_cluster = pd.read_csv('~/Documents/2020/new_pon_breast_phylo/1547_0915/1547_newer_bl_tree/1547.cluster_ccfs.txt',sep='\t',
                          low_memory=False)

pat_1558_cluster = pd.read_csv('~/Documents/2023/RA_1558_fix_pies/take_3/1558_fix_pies_v3/1558.cluster_ccfs.txt',sep='\t')

pat_2542_cluster = pd.read_csv('~/Documents/2023/RA_2542_PIK3CA/2542_high_purity_v6_morebl_moreiter_results/2542_high_purity_v6_morebl_moreiter.cluster_ccfs.txt',sep='\t')

pat_1045_cluster = pd.read_csv("/Users/lmartin/Documents/2020/new_pon_breast_phylo/1045_vm_phylo_results/1045.cluster_ccfs.txt",sep='\t')

pat_1113_cluster = pd.read_csv("/Users/lmartin/Documents/2020/new_pon_breast_phylo/1113_vm_phylo_results/1113.cluster_ccfs.txt",sep='\t')


pats_cluster_ccfs_list = [pat_1002_cluster, pat_1598_cluster, pat_1078_cluster, pat_1045_cluster, pat_1113_cluster,
            pat_1326_cluster, pat_1644_cluster, pat_2819_cluster, pat_2389_cluster, pat_2974_cluster, pat_1035_cluster, pat_1534_cluster,
                         pat_1547_cluster,pat_1558_cluster, pat_2542_cluster]

cluster_ccfs_df=pd.concat(pats_cluster_ccfs_list)

In [16]:
len(pats_cluster_ccfs_list)

15

In [37]:
pat_1113_cluster

,Patient_ID,Sample_ID,Sample_Alias,Cluster_ID,postDP_ccf_mean,postDP_ccf_CI_low,postDP_ccf_CI_high,postDP_ccf_0.0,postDP_ccf_0.01,postDP_ccf_0.02,...,postDP_ccf_0.91,postDP_ccf_0.92,postDP_ccf_0.93,postDP_ccf_0.94,postDP_ccf_0.95,postDP_ccf_0.96,postDP_ccf_0.97,postDP_ccf_0.98,postDP_ccf_0.99,postDP_ccf_1.0
0,1113,1,NaN,1,1.00,1.00,1.00,0.0,0.000000e+00,0.000000e+00,...,0.000000e+00,7.819250e-43,3.441740e-37,1.164410e-31,3.048820e-26,6.219410e-21,9.948290e-16,1.255180e-10,1.255520e-05,0.999985
1,1113,2,NaN,1,0.94,0.90,1.00,0.0,0.000000e+00,0.000000e+00,...,6.699890e-02,8.632680e-02,1.031680e-01,1.142410e-01,1.170910e-01,1.110370e-01,9.741440e-02,7.908500e-02,5.945110e-02,0.041350
2,1113,3,NaN,1,1.00,1.00,1.00,0.0,0.000000e+00,0.000000e+00,...,1.401300e-45,4.082070e-40,7.211180e-35,1.025990e-29,1.178130e-24,1.093640e-19,8.220820e-15,5.011920e-10,2.482420e-05,0.999977
3,1113,4,NaN,1,1.00,1.00,1.00,0.0,0.000000e+00,0.000000e+00,...,0.000000e+00,5.184800e-44,3.059240e-38,1.422220e-32,5.203340e-27,1.500310e-21,3.415800e-16,6.154800e-11,8.797720e-06,0.999992
4,1113,5,NaN,1,1.00,1.00,1.00,0.0,0.000000e+00,0.000000e+00,...,0.000000e+00,0.000000e+00,0.000000e+00,9.809090e-45,4.518150e-37,1.608940e-29,4.145490e-22,7.707420e-15,1.033920e-07,1.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60,1113,1,NaN,13,0.15,0.11,0.19,0.0,2.227380e-21,1.653290e-15,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000
61,1113,2,NaN,13,0.02,0.01,0.03,0.0,5.311980e-01,2.882980e-01,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000
62,1113,3,NaN,13,0.01,0.01,0.02,0.0,8.926680e-01,9.586060e-02,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000
63,1113,4,NaN,13,0.01,0.01,0.01,0.0,9.216160e-01,7.226740e-02,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000
64,1113,5,NaN,13,0.01,0.01,0.01,0.0,9.470990e-01,5.079790e-02,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000

### Buildtree Posteriors

In [17]:
def insert_pat_col(input_df, pat_id):
    patient_ID_col = [pat_id]*len(input_df)
    input_df.insert(loc=0,column='Patient_ID',value=patient_ID_col)
    return input_df

In [21]:
pat_1002_buildtree = pd.read_csv("/Users/lmartin/Documents/2020/new_pon_breast_phylo/1002_updated_apr21/1002_with_pre_post_build_tree_posteriors.tsv", sep='\t')
pat_1002_buildtree_add_pat = insert_pat_col(pat_1002_buildtree,'1002')

pat_1547_buildtree = pd.read_csv("/Users/lmartin/Documents/2020/new_pon_breast_phylo/1547_0915/1547_newer_bl_tree/1547_build_tree_posteriors.tsv", sep='\t')
pat_1547_buildtree_add_pat = insert_pat_col(pat_1547_buildtree,'1547')

pat_1078_buildtree = pd.read_csv("/Users/lmartin/Documents/2020/new_pon_breast_phylo/1078_new_pon_results/1078_build_tree_posteriors.tsv", sep='\t')
pat_1078_buildtree_add_pat = insert_pat_col(pat_1078_buildtree,'1078')

pat_1598_buildtree = pd.read_csv("/Users/lmartin/Documents/2020/new_pon_breast_phylo/1598_new_pon_results/1598_build_tree_posteriors.tsv", sep='\t')
pat_1598_buildtree_add_pat = insert_pat_col(pat_1598_buildtree,'1598')

pat_1326_buildtree = pd.read_csv("/Users/lmartin/Documents/2020/new_pon_breast_phylo/1326_firecloud_phylo/1326_cfDNA_high_purity_build_tree_posteriors.tsv", sep='\t')
pat_1326_buildtree_add_pat = insert_pat_col(pat_1326_buildtree,'1326')

pat_1644_buildtree = pd.read_csv("/Users/lmartin/Documents/2020/new_pon_breast_phylo/1644_passed_muts_results/1644_build_tree_posteriors.tsv", sep='\t')
pat_1644_buildtree_add_pat = insert_pat_col(pat_1644_buildtree,'1644')

pat_2819_buildtree = pd.read_csv("/Users/lmartin/Documents/2020/new_pon_breast_phylo/2819_passed_muts_results/2819_build_tree_posteriors.tsv", sep='\t')
pat_2819_buildtree_add_pat = insert_pat_col(pat_2819_buildtree,'2819')

pat_2389_buildtree = pd.read_csv("/Users/lmartin/Documents/2023/2389_multiple_6_bl_tree_0515/2389_multiple_6_bl_tree_v1/2389_multiple_6_build_tree_posteriors.tsv", sep='\t')
pat_2389_buildtree_add_pat = insert_pat_col(pat_2389_buildtree,'2389')

pat_2974_buildtree = pd.read_csv("/Users/lmartin/Documents/2020/new_pon_breast_phylo/2974_new_pon_results/2974_build_tree_posteriors.tsv", sep='\t')
pat_2974_buildtree_add_pat = insert_pat_col(pat_2974_buildtree,'2974')

pat_1534_buildtree = pd.read_csv("/Users/lmartin/Documents/2024/RA_1534_vm_new_bams/RA_1534_bl_TBX/1534_bl_TBX/1534_build_tree_posteriors.tsv", sep='\t')
pat_1534_buildtree_add_pat = insert_pat_col(pat_1534_buildtree,'1534')

pat_1035_buildtree = pd.read_csv("/Users/lmartin/Documents/2020/new_pon_breast_phylo/1035_with_indel/1035_build_tree_posteriors.tsv", sep='\t')
pat_1035_buildtree_add_pat = insert_pat_col(pat_1035_buildtree,'1035')

pat_1113_buildtree = pd.read_csv("/Users/lmartin/Documents/2020/new_pon_breast_phylo/1113_vm_phylo_results/1113_build_tree_posteriors.tsv", sep='\t')
pat_1113_buildtree_add_pat = insert_pat_col(pat_1113_buildtree,'1113')

pat_1045_buildtree = pd.read_csv("/Users/lmartin/Documents/2020/new_pon_breast_phylo/1045_vm_phylo_results/1045_build_tree_posteriors.tsv", sep='\t')
pat_1045_buildtree_add_pat = insert_pat_col(pat_1045_buildtree,'1045')

pat_1558_buildtree = pd.read_csv("/Users/lmartin/Documents/2023/RA_1558_fix_pies/take_3/1558_fix_pies_v3/1558_build_tree_posteriors.tsv", sep='\t')
pat_1558_buildtree_add_pat = insert_pat_col(pat_1558_buildtree,'1558')

pat_2542_buildtree = pd.read_csv('~/Documents/2023/RA_2542_PIK3CA/2542_high_purity_v6_morebl_moreiter_results/2542_high_purity_v6_morebl_moreiter_build_tree_posteriors.tsv',sep='\t')
pat_2542_buildtree_add_pat = insert_pat_col(pat_2542_buildtree,'2542')

buildtrees=[pat_1078_buildtree_add_pat,pat_1598_buildtree_add_pat,pat_1326_buildtree_add_pat,pat_1644_buildtree_add_pat,
            pat_2819_buildtree_add_pat,pat_2389_buildtree_add_pat,pat_2974_buildtree_add_pat,pat_1534_buildtree_add_pat,
            pat_1035_buildtree_add_pat,pat_1113_buildtree_add_pat,pat_1045_buildtree_add_pat,
           pat_1558_buildtree_add_pat,pat_2542_buildtree_add_pat]

buildtree_df = pd.concat(buildtrees)
buildtree_df

,Patient_ID,n_iter,likelihood,edges
0,1078,286,"[0.33333333333333337, 0.3333333333333332, 0.33...","1-2,2-3,2-4,2-5,None-1"
1,1078,270,"[0.5, 0.33333333333333331, 0.3333333333333332,...","1-2,1-4,2-3,2-5,None-1"
2,1078,234,"[0.3333333333333332, 0.5, 0.5, 0.3333333333333...","1-2,1-3,2-4,2-5,None-1"
3,1078,209,"[0.19999999999999998, 0.5, 0.19999999999999998...","1-2,1-5,2-3,2-4,None-1"
0,1598,28,"[0.14285714285714157, 0.24999999999999906, 0.4...","1-2,1-6,2-3,2-5,3-4,4-7,4-8,8-9,None-1"
...,...,...,...,...
38,2542,1,[0.24999999999999906],"1-4,1-5,2-7,2-12,3-6,3-9,4-2,4-3,5-8,5-14,6-10..."
39,2542,1,[0.19999999999999943],"1-4,1-5,2-3,2-7,3-6,3-9,4-2,5-8,5-11,6-10,6-15..."
40,2542,1,[0.19999999999999943],"1-4,1-5,2-3,2-7,3-6,3-9,4-2,4-15,5-8,5-14,6-10..."
41,2542,1,[0.19999999999999943],"1-4,1-5,2-3,2-7,3-6,3-9,4-2,4-10,5-8,5-11,6-15..."
42,2542,1,[0.24999999999999906],"1-4,1-5,2-3,2-7,3-6,3-9,4-2,4-10,5-8,6-16,7-12..."

## cell populations

In [22]:
pat_1002_cellpop = pd.read_csv("/Users/lmartin/Documents/2020/new_pon_breast_phylo/1002_updated_apr21/1002_with_pre_post_cell_population_abundances.tsv", sep='\t')

pat_1547_cellpop = pd.read_csv("/Users/lmartin/Documents/2020/new_pon_breast_phylo/1547_0915/1547_newer_bl_tree/1547_cell_population_abundances.tsv", sep='\t')

pat_1078_cellpop = pd.read_csv("/Users/lmartin/Documents/2020/new_pon_breast_phylo/1078_new_pon_results/1078_cell_population_abundances.tsv", sep='\t')
pat_1598_cellpop = pd.read_csv("/Users/lmartin/Documents/2020/new_pon_breast_phylo/1598_new_pon_results/1598_cell_population_abundances.tsv", sep='\t')

pat_1326_cellpop = pd.read_csv("/Users/lmartin/Documents/2020/new_pon_breast_phylo/1326_firecloud_phylo/1326_cfDNA_high_purity_cell_population_abundances.tsv", sep='\t')
pat_1644_cellpop = pd.read_csv("/Users/lmartin/Documents/2020/new_pon_breast_phylo/1644_passed_muts_results/1644_cell_population_abundances.tsv", sep='\t')

pat_2819_cellpop = pd.read_csv("/Users/lmartin/Documents/2020/new_pon_breast_phylo/2819_passed_muts_results/2819_cell_population_abundances.tsv", sep='\t')
pat_2389_cellpop = pd.read_csv("/Users/lmartin/Documents/2023/2389_multiple_6_bl_tree_0515/2389_multiple_6_bl_tree_v1/2389_multiple_6_cell_population_abundances.tsv", sep='\t')

pat_2974_cellpop = pd.read_csv("/Users/lmartin/Documents/2020/new_pon_breast_phylo/2974_new_pon_results/2974_cell_population_abundances.tsv", sep='\t')
pat_1534_cellpop = pd.read_csv("/Users/lmartin/Documents/2024/RA_1534_vm_new_bams/RA_1534_bl_TBX/1534_bl_TBX/1534_cell_population_abundances.tsv", sep='\t')

pat_1035_cellpop = pd.read_csv("/Users/lmartin/Documents/2020/new_pon_breast_phylo/1035_with_indel/1035_cell_population_abundances.tsv", sep='\t')

pat_1113_cellpop = pd.read_csv('/Users/lmartin/Documents/2020/new_pon_breast_phylo/1113_vm_phylo_results/1113_cell_population_abundances.tsv',sep='\t')
pat_1045_cellpop = pd.read_csv('/Users/lmartin/Documents/2020/new_pon_breast_phylo/1045_vm_phylo_results/1045_cell_population_abundances.tsv',sep='\t')

pat_1558_cellpop = pd.read_csv("/Users/lmartin/Documents/2023/RA_1558_fix_pies/take_3/1558_fix_pies_v3/1558_cell_population_abundances.tsv", sep='\t')


pat_2542_cellpop = pd.read_csv('~/Documents/2023/RA_2542_PIK3CA/2542_high_purity_v6_morebl_moreiter_results/2542_high_purity_v6_morebl_moreiter_cell_population_abundances.tsv',sep='\t')



cellpops=[pat_1002_cellpop,pat_1547_cellpop,pat_1078_cellpop,pat_1598_cellpop,pat_1326_cellpop,pat_1644_cellpop,pat_2819_cellpop,
         pat_2389_cellpop,pat_2974_cellpop,pat_1534_cellpop,pat_1035_cellpop,pat_1113_cellpop,
         pat_1045_cellpop,pat_1558_cellpop,pat_2542_cellpop]


cellpop_df = pd.concat(cellpops)
cellpop_df

,Patient_ID,Sample_ID,Cell_population,Cell_abundance
0,1002_with_pre_post,pre,CL1,78
1,1002_with_pre_post,pre,CL1_CL5,0
2,1002_with_pre_post,pre,CL1_CL6,18
3,1002_with_pre_post,pre,CL1_CL5_CL8,0
4,1002_with_pre_post,pre,CL1_CL6_CL10,0
...,...,...,...,...
75,2542_high_purity_v6_morebl_moreiter,2542_13,CL1_CL4_CL2_CL3_CL9_CL12,0
76,2542_high_purity_v6_morebl_moreiter,2542_13,CL1_CL4_CL2_CL3_CL6_CL13,0
77,2542_high_purity_v6_morebl_moreiter,2542_13,CL1_CL5_CL14,48
78,2542_high_purity_v6_morebl_moreiter,2542_13,CL1_CL4_CL15,0
79,2542_high_purity_v6_morebl_moreiter,2542_13,CL1_CL4_CL2_CL3_CL6_CL10_CL16,0

In [23]:
pat_1002_cellpop

             Patient_ID    Sample_ID        Cell_population  Cell_abundance
0    1002_with_pre_post          pre                    CL1              78
1    1002_with_pre_post          pre                CL1_CL5               0
2    1002_with_pre_post          pre                CL1_CL6              18
3    1002_with_pre_post          pre            CL1_CL5_CL8               0
4    1002_with_pre_post          pre           CL1_CL6_CL10               0
..                  ...          ...                    ...             ...
325  1002_with_pre_post  cfDNA_10351           CL1_CL5_CL16               7
326  1002_with_pre_post  cfDNA_10351       CL1_CL5_CL8_CL17               1
327  1002_with_pre_post  cfDNA_10351               CL1_CL18               1
328  1002_with_pre_post  cfDNA_10351      CL1_CL5_CL16_CL19               1
329  1002_with_pre_post  cfDNA_10351  CL1_CL5_CL8_CL14_CL20               0

[330 rows x 4 columns]

## Absolute CN by sample

In [ ]:
## current best file found needs added samples / patients

In [24]:
absolute_cn = pd.read_csv('/Users/lmartin/Documents/2020/autopsy_copy_number/all_cdk4_add_1035_igv.seg',sep='\t')
absolute_cn

,Sample,Chromosome,Start Position,End Position,Start,End,Num_Probes,Seg_CN
0,T01027-3,1,12176,94643659,12176,94643659,7210,0.000000
1,T01027-3,1,94645397,104160689,94645397,104160689,362,-1.000000
2,T01027-3,1,107599965,144363924,107599965,144363924,1207,0.000000
3,T01027-3,1,144520739,147131922,144520739,147131922,514,0.000000
4,T01027-3,1,147142061,147380734,147142061,147380734,3,-inf
...,...,...,...,...,...,...,...,...
18558,1035_20.tsv,21,9907370,31874299,9907370,31874299,321,1.000000
18559,1035_20.tsv,21,31914039,48084246,31914039,48084246,1348,0.584963
18560,1035_20.tsv,22,16287569,21567422,16287569,21567422,557,0.584963
18561,1035_20.tsv,22,21579761,25007131,21579761,25007131,372,0.000000
18562,1035_20.tsv,22,25019815,51237388,25019815,51237388,2500,0.000000

## Mutsig

### mutsig on pats

In [25]:
patients_sig_genes = pd.read_csv('/Users/lmartin/Documents/2023/CDK4_mutsig_added_pats/on_patients_v3/0/mutsig_results/outdir/sig_genes.txt',sep='\t')

patients_counts_and_rates = pd.read_csv('/Users/lmartin/Documents/2023/CDK4_mutsig_added_pats/on_patients_v3/0/mutsig_results/outdir/patient_counts_and_rates.txt',sep='\t')

### mutsig on clones

In [26]:
clones_sig_genes = pd.read_csv('/Users/lmartin/Documents/2023/CDK4_mutsig_added_pats/on_clones_v3/0/mutsig_results/outdir/sig_genes.txt',sep='\t')
clones_sig_genes.head(10)

,gene,longname,codelen,nnei,nncd,nsil,nmis,nstp,nspl,nind,...,npat,nsite,pCV,pCL,pFN,pCL2,pFN2,pCF,p,q
0,PIK3CA,"phosphoinositide-3-kinase, catalytic, alpha po...",3283,70,0,0,17,0,0,0,...,14,10,2.360248e-14,0.000002,0.018661,1.710987e-11,0.017422,NaN,1.000000e-16,1.818100e-12
1,ESR1,estrogen receptor 1,1901,48,1,2,9,0,0,1,...,10,5,2.569809e-11,0.000001,0.000964,3.290652e-05,0.001004,NaN,9.992007e-16,9.083234e-12
2,KMT2C,myeloid/lymphoid or mixed-lineage leukemia 3,15143,46,1,0,9,12,0,1,...,17,22,1.559657e-11,1.000000,0.702000,1.000000e+00,0.677212,NaN,4.037011e-10,2.446563e-06
3,TP53,tumor protein p53,1422,42,0,0,4,1,1,0,...,6,6,1.667200e-07,1.000000,0.122000,1.000000e+00,0.111691,NaN,5.411605e-07,2.459710e-03
4,KRAS,v-Ki-ras2 Kirsten rat sarcoma viral oncogene h...,727,167,0,0,3,0,0,0,...,3,2,1.064393e-04,0.007900,0.257300,4.094628e-03,0.255193,NaN,1.260366e-05,4.582945e-02
5,CTNNA2,"catenin (cadherin-associated protein), alpha 2",3166,43,1,1,4,0,0,0,...,4,2,4.602314e-02,0.000100,0.978105,3.969570e-07,0.978213,NaN,6.115993e-05,1.625311e-01
6,MNDA,myeloid cell nuclear differentiation antigen,1248,240,1,0,3,0,0,0,...,3,3,1.879589e-04,1.000000,0.011400,1.000000e+00,0.008556,NaN,6.257730e-05,1.625311e-01
7,HIST1H3B,"histone cluster 1, H3b",413,224,0,0,3,0,0,0,...,3,2,2.322263e-05,0.330000,0.846000,7.217303e-03,0.857143,NaN,9.793181e-05,2.225623e-01
8,ST18,suppression of tumorigenicity 18 (breast carci...,3221,72,2,0,4,0,0,0,...,4,3,1.321726e-02,0.004700,0.126567,1.859984e-03,0.130145,NaN,1.616998e-04,3.266516e-01
9,C12orf61,chromosome 12 open reading frame 61,396,31,0,0,2,0,0,0,...,2,2,2.579897e-03,1.000000,0.015200,9.999938e-01,0.015625,NaN,4.371024e-04,7.946958e-01

### mutsig on subclones

In [27]:
subclones_sig_genes = pd.read_csv('/Users/lmartin/Documents/2023/CDK4_mutsig_added_pats/on_subclones_v3/0/mutsig_results/outdir/sig_genes.txt',sep='\t')

In [28]:
subclones_sig_genes.head(10)

,gene,longname,codelen,nnei,nncd,nsil,nmis,nstp,nspl,nind,...,npat,nsite,pCV,pCL,pFN,pCL2,pFN2,pCF,p,q
0,ESR1,estrogen receptor 1,1901,48,1,2,8,0,0,1,...,9,5,1.218289e-10,0.000001,0.00166,2.304368e-05,0.001680,NaN,4.551914e-15,8.276291e-11
1,KMT2C,myeloid/lymphoid or mixed-lineage leukemia 3,15143,51,1,0,9,11,0,1,...,16,21,1.985128e-11,1.000000,0.74100,1.000000e+00,0.697105,NaN,5.090414e-10,4.627695e-06
2,TP53,tumor protein p53,1422,42,0,0,3,1,1,0,...,5,5,1.142566e-06,1.000000,0.07800,1.000000e+00,0.073564,NaN,1.867480e-06,1.131817e-02
3,KRAS,v-Ki-ras2 Kirsten rat sarcoma viral oncogene h...,727,174,0,0,3,0,0,0,...,3,2,4.243216e-05,0.005200,0.25680,4.094628e-03,0.255962,NaN,3.602442e-06,1.637490e-02
4,PIK3CA,"phosphoinositide-3-kinase, catalytic, alpha po...",3283,71,0,0,6,0,0,0,...,5,6,2.318574e-05,1.000000,0.03500,1.000000e+00,0.037330,NaN,2.664059e-05,9.687583e-02
5,MNDA,myeloid cell nuclear differentiation antigen,1248,240,1,0,3,0,0,0,...,3,3,1.537381e-04,1.000000,0.00850,1.000000e+00,0.007809,NaN,4.112391e-05,1.246192e-01
6,CTNNA2,"catenin (cadherin-associated protein), alpha 2",3166,23,1,1,4,0,0,0,...,4,2,3.832101e-02,0.000100,0.97867,3.969570e-07,0.978592,NaN,5.162644e-05,1.340960e-01
7,HIST1H3B,"histone cluster 1, H3b",413,224,0,0,2,0,0,0,...,2,1,3.643148e-04,0.067000,0.47000,2.409639e-03,0.472656,NaN,2.836472e-04,6.446591e-01
8,CSAD,cysteine sulfinic acid decarboxylase,1629,95,1,0,0,2,0,0,...,2,2,1.089837e-03,1.000000,0.02100,9.999996e-01,0.026402,NaN,4.703418e-04,9.501950e-01
9,ST18,suppression of tumorigenicity 18 (breast carci...,3221,72,2,0,3,0,0,0,...,3,2,4.784297e-02,0.001678,0.00173,9.303287e-04,0.001715,NaN,5.237650e-04,9.508162e-01

## clonesig results

In [33]:
clonesig_res =  pd.read_csv('/Users/lmartin/Documents/2023/CDK4_mutsig_added_pats/curveball_on_clones_with_mutsig_100923.tsv',sep='\t',index_col=0)
clonesig_res

        gene       p         q      MutSig_q    MutSig_qCV    log10q
2      KMT2C  0.0062  0.080600  2.446563e-06  1.417806e-07  1.093665
7   HIST1H3B  0.0139  0.090350  2.225623e-01  8.444213e-02  1.044072
11       FLG  0.0230  0.099667  1.000000e+00  3.373967e-01  1.001450
8       ST18  0.1289  0.359320  3.266516e-01  1.000000e+00  0.444519
3       TP53  0.1382  0.359320  2.459710e-03  7.577841e-04  0.444519
1       ESR1  0.2142  0.464100  9.083234e-12  1.557390e-07  0.333388
12      CLP1  0.2763  0.513129  1.000000e+00  4.991518e-01  0.289774
4       KRAS  0.3318  0.539175  4.582945e-02  2.934754e-01  0.268270
9      KLK13  0.4980  0.648440  1.000000e+00  2.934754e-01  0.188130
10    ADAM19  0.4988  0.648440  1.000000e+00  2.934754e-01  0.188130
6       MNDA  0.6242  0.698425  1.625311e-01  3.417281e-01  0.155880
5     CTNNA2  0.6447  0.698425  1.625311e-01  1.000000e+00  0.155880
0     PIK3CA  0.8864  0.886400  1.818100e-12  4.291167e-10  0.052370

In [34]:
only_clonesig = pd.read_csv('/Users/lmartin/Documents/2023/CDK4_mutsig_added_pats/curveball_on_clones.tsv',sep='\t')

## pre post mutsig on samples res

In [39]:
prepost_mutsig_res = pd.read_csv('/Users/lmartin/Documents/2024/CDK4_Pre_Post_Sample_Comut/PrePost_Mutsig/mutsig_results_pats_remove_junk1/outdir/sig_genes.txt',sep='\t')
prepost_mutsig_res.head(5)

,gene,longname,codelen,nnei,nncd,nsil,nmis,nstp,nspl,nind,...,npat,nsite,pCV,pCL,pFN,pCL2,pFN2,pCF,p,q
0,ESR1,estrogen receptor 1,1901,152,0,0,10,0,0,0,...,8,4,6.948777e-09,0.000003,0.001477,0.000015,0.001449,NaN,2.334799e-13,4.247933e-09
1,CDH1,"cadherin 1, type 1, E-cadherin (epithelial)",2709,45,0,0,1,1,0,3,...,5,5,6.672233e-07,0.007700,0.322000,1.000000,0.320227,NaN,9.426124e-08,8.574945e-04
2,GATA3,GATA binding protein 3,1351,31,0,1,1,0,0,4,...,5,5,1.157737e-07,1.000000,0.375000,1.000000,0.374832,NaN,8.713255e-07,5.284299e-03
3,TP53,tumor protein p53,1422,28,1,0,6,0,1,1,...,6,8,2.993179e-06,1.000000,0.009700,1.000000,0.010961,NaN,1.459206e-06,6.637199e-03
4,NAV1,neuron navigator 1,5848,46,1,5,2,0,0,2,...,4,3,5.111528e-03,0.002450,0.178400,0.001025,0.179907,NaN,6.427000e-05,2.338657e-01

## write all results to one spreadsheet

In [40]:
with pd.ExcelWriter('Extended_Data_Table2_Phylogic.xlsx') as writer:  
    #mut_ccfs_df.to_excel(writer, sheet_name='Phylogic MutCCFs')
    cluster_ccfs_df.to_excel(writer, sheet_name='Phylogic ClusterCCFs')
    buildtree_df.to_excel(writer, sheet_name='BuildTree Posteriors')
    cellpop_df.to_excel(writer, sheet_name='Cell Populations')
    absolute_cn.to_excel(writer, sheet_name='Sample_CNV')
    patients_sig_genes.to_excel(writer, sheet_name='Mutsig_Patients')
    clones_sig_genes.to_excel(writer, sheet_name='Mutsig_Clones')
    subclones_sig_genes.to_excel(writer, sheet_name='Mutsig_Subclones')
    clonesig_res.to_excel(writer, sheet_name='CloneSig')
    prepost_mutsig_res.to_excel(writer, sheet_name='PrePost_Mutsig')

## write results without the mutation files because those are big